### ISSUE TITLE
Travis: send mail to commiter if build fails

### ISSUE THREAD

**Issue by etsardou** [rapp-project/rapp-platform#196]

**Comment by athallas** [comment]
As specified [here](https://docs.travis-ci.com/user/notifications/#How-is-the-build-email-receiver-determined%3F) the default behavior is to notify the commiter and the author. However, since in the [travis.yaml](https://github.com/rapp-project/rapp-platform/blob/master/.travis.yml) file another recipient has been specified, the default behavior is canceled and only the specified recipient is notified.

I would suggest removing the following lines from the travis configuration file:
```
notifications:
  email:
    recipients:
      - etsardou@gmail.com
    on_success: always #[always|never|change] # default: change
    on_failure: always #[always|never|change] # default: always
```
